<?php
/**
 * @file
 * imagex_addthis.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function imagex_addthis_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_addthis'
  $field_bases['field_addthis'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_addthis',
    'foreign keys' => array(),
    'indexes' => array(),
    'locked' => 0,
    'module' => 'addthis',
    'settings' => array(
      'max_length' => 255,
    ),
    'translatable' => 0,
    'type' => 'addthis',
  );

  return $field_bases;
}
